// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents


PicklistsManagerUtils.deployPicklist('a001j000005iQd6AAE');
PicklistsManagerUtils.deployPicklistDependency('a041j000008kx1oAAA');